### ISSUE TITLE
Undo reversion of .Call() arguments

### ISSUE THREAD

**Issue by richierocks** [baddstats/polyclip#10]
You may recall that ployclip is used in the [Spatial Statistics in R](https://www.datacamp.com/courses/spatial-statistics-in-r) DataCamp course. Last year, when we were making that course, I made some updates to polyclip's `.Call()` routines to add a `PACKAGE` argument. This was necessary to make the package work on our platform.

I've just been making some updates to that course and unfortunately, the latest version of polyclip doesn't work. It look like the changes to `.Call()` were reverted back in March.

https://github.com/baddstats/polyclip/commit/f1fff8cc3cf1ea0bf4a6f968d883dbd28881353a#diff-c0145812160455f0558c81a96c08e975

Is there a reason for this? Are you happy to undo the reversion?

**Comment by baddstats** [comment]
Incompetence is the reason!!
It will be fixed asap

**Comment by baddstats** [comment]
Done
