### ISSUE TITLE
Installation failed from CRAN

### ISSUE THREAD

**Issue by zhiruiwang** [baddstats/polyclip#11]
I am using Microsoft R Open 3.5 on MacOS 10.13.5 and want to install polyclip from CRAN, but it failed. The error log is like the following:
```
* installing *source* package ‘polyclip’ ...
** package ‘polyclip’ successfully unpacked and MD5 sums checked
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
compiling under C++11
Using PKG_CONFIG: 
Compiling against bundled copy of clipper library.
     In the clipper library, signed 64-bit integers (cInt)
     will be declared as 'signed long long'
     In the clipper library, unsigned 64-bit integers (cUInt)
     will be declared as 'unsigned long long'
configure: creating ./config.status
config.status: creating src/Makevars
** libs
Makevars:3: *** target pattern contains no `%'.  Stop.
ERROR: compilation failed for package ‘polyclip’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5.0-MRO/Resources/library/polyclip’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5.0-MRO/Resources/library/polyclip’
Warning in install.packages :
  installation of package ‘polyclip’ had non-zero exit status
```
However, if I install the package from GitHub `install_github('baddstats/polyclip')`, everything works fine. I wonder whether it is because the version on CRAN has some minor issues?
```
> devtools::install_github('baddstats/polyclip')
Downloading GitHub repo baddstats/polyclip@master
from URL https://api.github.com/repos/baddstats/polyclip/zipball/master
Installing polyclip
'/Library/Frameworks/R.framework/Resources/bin/R'  \
  --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/private/var/folders/1v/wz_prgn52n91b5x1byjxwnl00000gn/T/RtmphT10uh/devtools14e468d99c59/baddstats-polyclip-d5dc5e2'  \
  --library='/Library/Frameworks/R.framework/Versions/3.5.0-MRO/Resources/library'  \
  --install-tests 

* installing *source* package ‘polyclip’ ...
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
compiling under C++11
Using PKG_CONFIG: 
Compiling against bundled copy of clipper library.
     In the clipper library, signed 64-bit integers (cInt)
     will be declared as 'signed long long'
     In the clipper library, unsigned 64-bit integers (cUInt)
     will be declared as 'unsigned long long'
configure: creating ./config.status
config.status: creating src/Makevars
** libs
/usr/local/clang4/bin/clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -DPOLYCLIP_LONG64="signed long long" -DPOLYCLIP_ULONG64="unsigned long long"  -DU_STATIC_IMPLEMENTATION -Wall -mtune=core2 -g -O2 -I/opt/X11/include   -fPIC  -DU_STATIC_IMPLEMENTATION -Wall -mtune=core2 -g -O2 -I/opt/X11/include  -c init.c -o init.o
/usr/local/clang4/bin/clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -DPOLYCLIP_LONG64="signed long long" -DPOLYCLIP_ULONG64="unsigned long long"  -DU_STATIC_IMPLEMENTATION -Wall -mtune=core2 -g -O2 -I/opt/X11/include  -DU_STATIC_IMPLEMENTATION -Wall -mtune=core2 -g -O2 -I/opt/X11/include -fPIC  -DU_STATIC_IMPLEMENTATION -Wall -mtune=core2 -g -O2 -I/opt/X11/include -c interface.cpp -o interface.o
/usr/local/clang4/bin/clang++ -std=gnu++11 -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -DPOLYCLIP_LONG64="signed long long" -DPOLYCLIP_ULONG64="unsigned long long"  -DU_STATIC_IMPLEMENTATION -Wall -mtune=core2 -g -O2 -I/opt/X11/include  -DU_STATIC_IMPLEMENTATION -Wall -mtune=core2 -g -O2 -I/opt/X11/include -fPIC  -DU_STATIC_IMPLEMENTATION -Wall -mtune=core2 -g -O2 -I/opt/X11/include -c clipper.cpp -o clipper.o
/usr/local/clang4/bin/clang++ -std=gnu++11 -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib/gcc/7 -o polyclip.so init.o interface.o clipper.o -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.5.0-MRO/Resources/library/polyclip/libs
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (polyclip)
```

**Comment by baddstats** [comment]
Sorry, we don't run any Microsoft systems, so we cannot debug this. The development version of polyclip is currently *identical* to the CRAN version (1.9-0). The CRAN version passes all the CRAN checks under Windows. So this would appear to be a problem with "Microsoft R Open".

**Comment by baddstats** [comment]
Sorry, I meant that the CRAN version of polyclip passes all the CRAN package checks on **MacOS** using the definitive version of **R for MacOS**. So this would appear to be a problem with "Microsoft R Open for MacOS" which we don't support.

**Comment by rubak** [comment]
Furthermore, I think you should report this to Microsoft R Open since I believe they aim at supporting all CRAN packages that work in GNU R, so they are probably interested in tracking down the problem. As @baddstats points out there isn't much we can do about it at this point.

**Comment by iembry** [comment]
Hi, the CRAN version of polyclip on a GNU/Linux Ubuntu-based distribution has failed for me.

I have not tried the GitHub version yet.

    > install.packages("polyclip")
    Installing package into ‘library’
    (as ‘lib’ is unspecified)
    trying URL 'https://cloud.r-project.org/src/contrib/polyclip_1.9-0.tar.gz'
    Content type 'application/x-gzip' length 78996 bytes (77 KB)
    ==================================================
    downloaded 77 KB
    
    * installing *source* package ‘polyclip’ ...
    ** package ‘polyclip’ successfully unpacked and MD5 sums checked
    checking for g++... g++
    checking whether the C++ compiler works... yes
    checking for C++ compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C++ compiler... yes
    checking whether g++ accepts -g... yes
    compiling under C++11
    Using PKG_CONFIG: pkg-config
    Compiling against system copy of polyclipping library.
    configure: creating ./config.status
    config.status: creating src/Makevars
    ** libs
    ccache gcc -I"/usr/share/R/include" -DNDEBUG -I/usr/include/polyclipping   -DPOLYCLIP_LONG64="signed long long" -DPOLYCLIP_ULONG64="unsigned long long"     -fpic  -std=gnu99 -Wall -pedantic -c init.c -o init.o
    ccache g++ -std=c++11 -I"/usr/share/R/include" -DNDEBUG -I/usr/include/polyclipping   -DPOLYCLIP_LONG64="signed long long" -DPOLYCLIP_ULONG64="unsigned long long"    -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c interface.cpp -o interface.o
    ccache g++ -std=c++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o polyclip.so init.o interface.o -lpolyclipping -L/usr/lib/R/lib -lR
    installing to library/polyclip/libs
    ** R
    ** byte-compile and prepare package for lazy loading
    ** help
    *** installing help indices
    ** building package indices
    ** testing if installed package can be loaded
    Error: package or namespace load failed for ‘polyclip’ in dyn.load(file, DLLpath = DLLpath, ...):
     unable to load shared object 'library/polyclip/libs/polyclip.so':
      library/polyclip/libs/polyclip.so: undefined symbol: _ZN10ClipperLib12MinkowskiSumERKSt6vectorINS_8IntPointESaIS1_EERKS0_IS3_SaIS3_EERS7_b
    Error: loading failed
    Execution halted
    ERROR: loading failed
    * removing ‘library/polyclip’
    
    The downloaded source packages are in
            ‘/tmp/Rtmp2qGS9a/downloaded_packages’
    Warning message:
    In install.packages("polyclip") :
      installation of package ‘polyclip’ had non-zero exit status

**Comment by baddstats** [comment]
@iembry, this is a different issue from the one reported by @zhiruiwang.

The `polyclip` package includes all the required C++ code for the clipper library. However, if another version of the clipper C++ library (namely the `polyclipping` C++ library) is already installed on the system, then the installation will use the already-installed one. The output in the message from @iembry includes the line `Compiling against system copy of polyclipping library` which indicates that it is using an already-installed version of `polyclipping`. Apparently there is an incompatibility between that system-installed code and the R package `polyclip`. We have no control over this, unfortunately. 

The option to compile against an already-installed library was added by a contributor. I will see if he is willing to help.
