### ISSUE TITLE
Clipping of paths

### ISSUE THREAD

**Issue by thomasp85** [baddstats/polyclip#4]
As it is now, `polyclip()` consider the input paths closed. Would you consider either making a switch to control how the paths should be considered or make a `polylineclip()` function as well?

**Comment by baddstats** [comment]
OK. Will do.

**Comment by thomasp85** [comment]
Are you still planning on implementing this when time permits? It would be a very nice addition

**Comment by rubak** [comment]
Does the recent PR by @pmur002 solve this issue as well? It sounds like the same feature request to me.

**Comment by thomasp85** [comment]
It appears so. Thanks!
