### ISSUE TITLE
Error when compiling package in Ubuntu 16.04

### ISSUE THREAD

**Issue by ipuzek** [baddstats/polyclip#9]
Console output:

* installing *source* package ‘polyclip’ ...
** package ‘polyclip’ successfully unpacked and MD5 sums checked
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
compiling under C++11
Using PKG_CONFIG: pkg-config
Compiling against bundled copy of clipper library.
     In the clipper library, signed 64-bit integers (cInt)
     will be declared as 'signed long long'
     In the clipper library, unsigned 64-bit integers (cUInt)
     will be declared as 'unsigned long long'
configure: creating ./config.status
config.status: creating src/Makevars
** libs
Makevars:3: *** missing separator. Stop.
ERROR: compilation failed for package ‘polyclip’

**Comment by rubak** [comment]
Which version of R is this under? And are you just installing the CRAN version of `polyclip` via `install.packages()`?

**Comment by gregleleu** [comment]
Hi, 
same issue on OS X
Unclear what causes it

> remotes::install_github('baddstats/polyclip')
Downloading GitHub repo baddstats/polyclip@master
* installing *source* package ‘polyclip’ ...
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
Error: unexpected end of input
Execution halted
compiling under C++11
Using PKG_CONFIG: pkg-config
Compiling against bundled copy of clipper library.
     In the clipper library, signed 64-bit integers (cInt)
     will be declared as 'signed long long'
     In the clipper library, unsigned 64-bit integers (cUInt)
     will be declared as 'unsigned long long'
configure: creating ./config.status
config.status: creating src/Makevars
** libs
Makevars:4: *** missing separator.  Stop.
ERROR: compilation failed for package ‘polyclip’
* removing ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/polyclip’
* restoring previous ‘/Library/Frameworks/R.framework/Versions/3.5/Resources/library/polyclip’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/dj/syp3v_s56_j7j6n56plgzwy00000gn/T//RtmpmlWKuA/remotesd5f1440d6dc6/baddstats-polyclip-afa1dfa’ had non-zero exit status
>

**Comment by gregleleu** [comment]
Here's my sessionInfo():

R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0

**Comment by rubak** [comment]
I have now found the bug in the configure script and (hopefully) fixed it. Could you please confirm that it now works and close the issue?

**Comment by luisspuerto** [comment]
did you already uploaded to CRAN? I still have the same issue in macOS.

**Comment by rubak** [comment]
No, not on CRAN yet. Please install from GitHub:

    remotes::install_github('baddstats/polyclip')

**Comment by luisspuerto** [comment]
Now build perfectly 👍
